### ISSUE TITLE
Add functionality to search/filter function

### ISSUE THREAD

**Issue by coral-412** [AcademyPgh/Y3S1-ReplayFX#33]

**Comment by ekjensen** [comment]
Maybe look into anchor tags?

**Comment by ironpencil** [comment]
The workflow for this should probably go something like this:

1. TextInput component with an onChangeText prop that calls setState and sets some kind of state.searchFilter to the change value. It should also have a value prop that is equal to this.state.searchFilter. Something like this: <TextInput onChangeText={(text) => this.setState({searchFilter: text})} value={this.state.searchFilter} />

2. The section of the code that maps the gameList array to the components should have a .filter() function on the array that checks if this.state.searchFilter is blank, or if it's not blank, if the game name starts with the search term (or maybe just contains the search term). If this.state.searchFilter is blank or the game name starts with it, return true, and that game will be included in the filter. All other games will be filtered out. The games that match will simply be passed on to the map function, and anything that doesn't will not be displayed.

**Comment by ekjensen** [comment]
Alright folks, I'm going to take a stab at this

**Comment by coral-412** [comment]
Look at: https://www.npmjs.com/package/react-native-search-bar
and 
https://react-native-training.github.io/react-native-elements/docs/searchbar.html

**Comment by ironpencil** [comment]
I mean that does what we need it, but I don't imagine implementing that is going to be much easier than just using a plain TextInput function. The Clear button is nice. Look here for a sample: https://facebook.github.io/react-native/docs/handling-text-input.html

**Comment by ironpencil** [comment]
- [ ] TextInput component that, when text is changed, stores the changed text in this.state.searchTerm. The textinput component's value should also be set to this.state.searchTerm, so that when the searchTerm is updated, the text input's value updates.
- [ ] In the scrollview that displays the games, in the filter() method that is checking to see if a game is an Arcade game, add a step that checks if this.state.searchTerm is not blank. If it is not blank, then filter() should only return true if the game is an arcade game AND the game name contains this.state.searchTerm.
